### ISSUE TITLE
Just Comments

### ISSUE THREAD

**Issue by JamesDunne** [andrewrk/jamulator#2]
I wanted to leave a comment on your blog post but didn't find any way to do that, so here I am in GitHub making an 'issue'. I hope you don't mind. :)

I figure that your work on this project would be great to aid in "porting" a NES game's gameplay and mechanics into a native port or variant of the same game. For example, I would use this to recompile, say, bits of Blaster Master's engine code to a PC game and then build a custom input/display system around that core logic instead of trying to include emulation of the PPU and APU of the NES.

**Comment by andrewrk** [comment]
I think that makes a lot of sense.

**Comment by JamesDunne** [comment]
I'd love to see you take a whack at moving the SMB1 gameplay over to a native port in that fashion. Like you said in your blog post, I'm not sure you'd be able to get much further with the approach of making a full-fledged emulator via static recompilation.

Do NES games typically page in new code via mappers or is that just for data only? If so, that would be another tricky problem to overcome.

**Comment by andrewrk** [comment]
There's not really much of a distinction between data and code in this kind of assembly. To answer your question, yes, new code as well as data is paged in.

I will likely not be continuing this project at least for a while. I'll be moving on to some other pursuits.

**Comment by JamesDunne** [comment]
Cool. I'll just close this issue. Nice work, though! I enjoyed reading the write-up.

**Comment by andrewrk** [comment]
Thanks, I'm glad you enjoyed it.
